"""add article_categories and article status/category_id

Revision ID: 021e39405e98
Revises: d1155b474665
Create Date: 2026-08-20 02:43:03.565575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '021e39405e98'
down_revision: Union[str, Sequence[str], None] = 'd1155b474665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.alter_column('published',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_articles_category_published'))
        batch_op.create_index('ix_articles_category_published', ['category_id', 'published'], unique=False)
        batch_op.create_foreign_key('fk_articles_category_id_article_categories', 'article_categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_articles_category_id_article_categories', type_='foreignkey')
        batch_op.drop_index('ix_articles_category_published')
        batch_op.create_index(batch_op.f('ix_articles_category_published'), ['category', 'published'], unique=False)
        batch_op.alter_column('published',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('category_id')

    op.drop_table('article_categories')
    # ### end Alembic commands ###
