"""add boards tables and migrate forum/column to board_id

Revision ID: d1155b474665
Revises: 00e5147eaf9f
Create Date: 2026-08-20 01:31:03.570016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1155b474665'
down_revision: Union[str, Sequence[str], None] = '00e5147eaf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('boards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('require_certified', sa.Boolean(), nullable=False),
    sa.Column('daily_post_limit', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('board_bans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('board_bans', schema=None) as batch_op:
        batch_op.create_index('ix_board_bans_board_user', ['board_id', 'user_id'], unique=False)

    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_columns_board_id_boards', 'boards', ['board_id'], ['id'])
        batch_op.drop_column('board_tag')

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_forum_posts_cat_pinned_id'))
        batch_op.create_index('ix_forum_posts_board_pinned_id', ['board_id', 'is_pinned', 'id'], unique=False)
        batch_op.create_foreign_key('fk_forum_posts_board_id_boards', 'boards', ['board_id'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint('fk_forum_posts_board_id_boards', type_='foreignkey')
        batch_op.drop_index('ix_forum_posts_board_pinned_id')
        batch_op.create_index(batch_op.f('ix_forum_posts_cat_pinned_id'), ['category_id', 'is_pinned', 'id'], unique=False)
        batch_op.drop_column('board_id')

    with op.batch_alter_table('columns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_tag', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint('fk_columns_board_id_boards', type_='foreignkey')
        batch_op.drop_column('board_id')

    with op.batch_alter_table('board_bans', schema=None) as batch_op:
        batch_op.drop_index('ix_board_bans_board_user')

    op.drop_table('board_bans')
    op.drop_table('boards')
    op.drop_table('board_applications')
    # ### end Alembic commands ###
