FORUM_TABLE_PLAN = {
    "forum_posts": [
        "id",
        "author_id",
        "category_id",
        "title",
        "excerpt",
        "content",
        "tags",
        "is_pinned",
        "is_featured",
        "view_count",
        "like_count",
        "comment_count",
        "bookmark_count",
        "created_at",
        "updated_at",
    ],
    "forum_comments": [
        "id",
        "post_id",
        "user_id",
        "content",
        "floor_number",
        "parent_id",
        "like_count",
        "created_at",
    ],
}
